### ISSUE TITLE
[Question] Setting up workspace for this mod

### ISSUE THREAD

**Issue by Elsys656** [amadornes/Framez#42]
So I grabbed IntelliJ and java 8 sdk, followed the tutorial for setting up in forge, I have unresolved symbols for some vector library and I think trajectory. Basically I just wanted to see if I could help fix some things and maybe create an addon for this mod because it's the most stable feature rich version of frame related mods I've found. Tried the latest of RiM and FunkyLocomotion funky is very stable but doesn't have everything this does and RiM has lots of bugs in comparison. Also the block textures in this version are quite a bit better as well as the way it handles multipart is quite a bit better as well. The last time I modded anything for minecraft is back when server/client were separated and you had to use MCP and forge separately to set things up. I have followed the latest tutorial by diesieben07 to set up my intelliJ workspace and like I said i'm running into a wall when it comes to resolving everything to build.

**Comment by amadornes** [comment]
Ah, yes... Setting up a workspace... I should've mentioned before that the latest version of the code isn't up on github xD
I'll upload it as soon as the last few bugs are fixed, which will hopefully be in less than a week :)

**Comment by JasonMcRay** [comment]
@amadornes Any info on when you will put out the Framez 2 code on github? I guess you are moving to 1.8/.19 development, but I would like to get my hands on the code and do some fixes, changes (mainly disabling the world gen of metamorphic stone)

**Comment by amadornes** [comment]
@JasonMcRay I'll do it today, if I don't forget... If I do, poke me on IRC (#Framez), Twitter, or just here. I'll also push Trajectory (to its own repo). I'm sorry I haven't been able to release the fixed build I promised a while ago but I haven't had much free time lately nor have I found any motivation to even touch 1.7.10 anymore.
Luckily for you, the code for Framez 3 is already up in its own branch and will be updated as development progresses, unlike what happened with F2 where I ended up keeping the source to myself because it wasn't completely finished, so making a PR with bugfixes and things like that will be doable... but only for F3. I'll take PRs for F2 once the code is up, though :)

**Comment by JasonMcRay** [comment]
Ok..Succesfully grabbed all dependencies, no compiler error for Framez 2.

However crash right from the start: 
http://pastebin.com/AnK3argp

Isnt possible that you forgot to push some files? :)

**Comment by amadornes** [comment]
It's there (https://goo.gl/MP2ZlV), so as long as you're compiling it as a scala project (I had to write some classes in scala to get around some oddities in FMP) it should work just fine :P

**Comment by amadornes** [comment]
If you need any help, I'll be on IRC all day: #Framez on esper.net

**Comment by JasonMcRay** [comment]
I guess my IDEA instance is bit wonky with Scala... will try it in eclipse

**Comment by GirafiStudios** [comment]
@JasonMcRay you have to have the IntelliJ Scala Plugin. It might not be installed by default.

**Comment by JasonMcRay** [comment]
I do have it installed, thats what confusing me

**Comment by jesmores** [comment]
Is this still happening? I'd love for #33 to be resolved if possible :<
